# Generated by Django 3.1.4 on 2020-12-14 08:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('surname', models.CharField(max_length=125)),
                ('dateOfBirth', models.DateField(default=django.utils.timezone.now)),
                ('login', models.CharField(max_length=16, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('isDeleted', models.BooleanField(default=False)),
            ],
        ),
    ]
